"""Observation triage — Alice reads unstructured observations and produces a conversational
response per the brief's "conversational, not triaged" doctrine.

Reads:  feedback/observations.md (Alice processes any entries since last triage)
Writes: feedback/threads/<id>.md (one thread per observation, Alice's response in it)
        feedback/proposed/<id>.md (for changes that need approval — additive vs subtractive)
        feedback/applied/<id>.md (for auto-applied additive changes)
        Updates feedback/triage-state.json (last_processed_ts)

The actual response is generated by an LLM call with Alice.md as system prompt + the observation
+ relevant context (sheet snapshot, recent activity, codebase scope). Alice decides per-observation
whether to act, propose, ask, or push back.
"""
import json
import re
import sys
from datetime import datetime
from pathlib import Path

from alice import repo_paths
from alice.llm import llm
from alice import safe_state

OBS_LOG = Path(str(repo_paths.FEEDBACK / "observations.md"))
THREADS_DIR = Path(str(repo_paths.FEEDBACK / "threads"))
PROPOSED_DIR = Path(str(repo_paths.FEEDBACK / "proposed"))
TRIAGE_STATE = Path(str(repo_paths.FEEDBACK / "triage-state.json"))
_TRIAGE_DEFAULT = {"last_processed_ts": None, "thread_counter": 0}


def _load_triage_state():
    return safe_state.atomic_read(TRIAGE_STATE, default=dict(_TRIAGE_DEFAULT))


def _save_triage_state(state):
    safe_state.atomic_write(TRIAGE_STATE, state)


def _parse_observations():
    """Read observations.md and split into entries.
    Each entry: {ts, reply_to_subject, structured_count, text, ts_iso}."""
    if not OBS_LOG.exists():
        return []
    text = OBS_LOG.read_text()
    entries = []
 # Split on entry headers: \n---\n## YYYY-MM-DD HH:MM · reply to: '...'
    parts = re.split(r"\n---\n## ", text)
    for raw in parts[1:]:  # skip preamble
        header_match = re.match(r"(\d{4}-\d{2}-\d{2} \d{2}:\d{2})\s+·\s+reply to:\s+'([^']*)'(?:\s+·\s+\((\d+) status updates? also applied\))?",
                                 raw)
        if not header_match:
            continue
        ts_str = header_match.group(1)
        subject = header_match.group(2)
        struct_count = int(header_match.group(3)) if header_match.group(3) else 0
 # body starts after header line
        body_start = raw.find("\n", header_match.end())
        body = raw[body_start:].strip() if body_start >= 0 else ""
        try:
            ts_iso = datetime.strptime(ts_str, "%Y-%m-%d %H:%M").isoformat(timespec="seconds")
        except Exception:
            ts_iso = None
        entries.append({
            "ts":               ts_str,
            "ts_iso":           ts_iso,
            "reply_to_subject": subject,
            "structured_count": struct_count,
            "text":             body,
        })
    return entries


def _new_thread_id(state):
    state["thread_counter"] = state.get("thread_counter", 0) + 1
    return f"thread-{datetime.now().strftime('%Y%m%d')}-{state['thread_counter']:03d}"


def _build_context_for_alice(observation):
    """Build the prompt context Alice needs to triage well: the observation itself,
    a snapshot of current sheet state, focus list, recent activity. Kept compact —
    no need to dump everything."""
    import ledger, focus
    try:
        rows = ledger._ws().get_all_records()
    except Exception:
        rows = []
    by_status = {}
    for r in rows:
        s = (r.get("status") or "new").strip().lower()
        by_status[s] = by_status.get(s, 0) + 1
    sheet_summary = ", ".join(f"{k}={v}" for k, v in sorted(by_status.items())) or "empty"
    focus_list = focus.status_for_focus()
    focus_summary = "; ".join(f"{f['company']}({f['status']})" for f in focus_list) or "(empty)"
    return {
        "sheet_summary": sheet_summary,
        "focus_summary": focus_summary,
        "total_rows":    len(rows),
    }


def _triage_one(observation, thread_id):
    """Ask Alice (via LLM) to respond to one observation. Returns dict with response text +
    classification (auto_apply | propose | ask | push_back | acknowledge) + any proposed patch."""
    ctx = _build_context_for_alice(observation)
    brief = llm.load_alice_brief()
    user_prompt = f"""You are responding to an observation Jordan Avery sent in a digest reply.

YOUR FULL BRIEF is loaded as your system prompt — re-read the relevant sections (especially
"Process improvement", "Decision principles", "What she will not do", "Additive-only constraint",
and "Per-application strategic execution") before responding.

Current context:
  Sheet rows: {ctx['total_rows']} ({ctx['sheet_summary']})
  Focus list: {ctx['focus_summary']}
  Reply timestamp: {observation['ts']}
  In response to digest subject: {observation['reply_to_subject']!r}

OBSERVATION FROM JORDAN AVERY:
\"\"\"
{observation['text']}
\"\"\"

Produce your response in this EXACT format:

CLASSIFICATION: <one of: auto_apply | propose | ask | push_back | acknowledge>
SUMMARY: <one-sentence summary of what Jordan Avery said, in your words>

RESPONSE:
<your actual reply to Jordan Avery, in your voice. This is what he'll read in the next digest.
Direct, evidence-driven, no em dashes, no consulting-speak. If you disagree, disagree.
If you need more info, ask. If you can act now within additive-only constraint, say what
you'll do. If a change is subtractive (filter, threshold, suppression), propose with
the diff and queue for his approval.>

PROPOSED_PATCH:
<if classification is propose or auto_apply, describe the specific code/state change
in plain English. Name files, functions, or state structures involved. If classification
is ask, push_back, or acknowledge, write "none".>

NEXT_STEP_FROM_OPERATOR:
<the single concrete thing Jordan Avery needs to do next, if anything. Specific reply syntax if he
needs to send one. "none" if no action needed from him.>
"""
    res = llm.call(
        task="triage_observation",
        prompt=user_prompt,
        system=brief,
        max_tokens=1500,
    )
    return _parse_alice_response(res["text"]), res


def _parse_alice_response(text):
    """Extract the structured fields from Alice's response."""
    out = {"classification": "acknowledge", "summary": "", "response": text, "proposed_patch": "none", "next_step": "none"}
    m = re.search(r"CLASSIFICATION:\s*(\w+)", text, re.I)
    if m:
        out["classification"] = m.group(1).lower()
    m = re.search(r"SUMMARY:\s*(.+?)(?:\n|$)", text, re.I)
    if m:
        out["summary"] = m.group(1).strip()
    m = re.search(r"RESPONSE:\s*\n(.+?)(?=\nPROPOSED_PATCH:|\Z)", text, re.S | re.I)
    if m:
        out["response"] = m.group(1).strip()
    m = re.search(r"PROPOSED_PATCH:\s*\n(.+?)(?=\nNEXT_STEP_FROM_OPERATOR:|\Z)", text, re.S | re.I)
    if m:
        out["proposed_patch"] = m.group(1).strip()
    m = re.search(r"NEXT_STEP_FROM_OPERATOR:\s*\n(.+?)\Z", text, re.S | re.I)
    if m:
        out["next_step"] = m.group(1).strip()
    return out


def _write_thread(observation, thread_id, alice_response, llm_meta):
    """Persist the thread to feedback/threads/<id>.md."""
    THREADS_DIR.mkdir(parents=True, exist_ok=True)
    path = THREADS_DIR / f"{thread_id}.md"
    content = f"""# {thread_id}

**Created:** {datetime.now().isoformat(timespec='seconds')}
**Reply to digest:** {observation['reply_to_subject']!r}
**Jordan Avery's observation timestamp:** {observation['ts']}
**Status:** open
**Classification:** {alice_response['classification']}
**LLM:** {llm_meta['model']} ({llm_meta['in_tokens']}+{llm_meta['out_tokens']} tokens, ${llm_meta['cost_usd']:.5f})

## Jordan Avery's observation
{observation['text']}

## Alice's summary
{alice_response['summary']}

## Alice's response (this goes in the next digest)
{alice_response['response']}

## Proposed patch
{alice_response['proposed_patch']}

## Next step from Jordan Avery
{alice_response['next_step']}

---

## Conversation log
(future replies from Jordan Avery on this thread get appended below)
"""
    path.write_text(content)
    return path


def _maybe_propose(observation, thread_id, alice_response):
    """If classification is 'propose', also write to feedback/proposed/ for the approve/reject queue."""
    if alice_response["classification"] != "propose":
        return None
    PROPOSED_DIR.mkdir(parents=True, exist_ok=True)
    prop_id = thread_id.replace("thread-", "proposal-")
    path = PROPOSED_DIR / f"{prop_id}.md"
    content = f"""# {prop_id}

**Source thread:** {thread_id}
**Jordan Avery's observation:** {observation['text'][:300]}
**Created:** {datetime.now().isoformat(timespec='seconds')}
**Expires:** {(datetime.now().date() + __import__('datetime').timedelta(days=7)).isoformat()}

## Alice's summary
{alice_response['summary']}

## Proposed patch
{alice_response['proposed_patch']}

## Approve / reject

Reply with `approve {prop_id}` to apply, or `reject {prop_id}` (optionally with reason).
"""
    path.write_text(content)
    return path


def main():
    """Process all observations newer than triage-state's last_processed_ts."""
    state = _load_triage_state()
    last_ts = state.get("last_processed_ts")
    entries = _parse_observations()
    new_entries = [e for e in entries if not last_ts or (e["ts_iso"] and e["ts_iso"] > last_ts)]

    if not new_entries:
        print("[triage: no new observations]")
        try:
            from alice.persistence import activity_log
            activity_log.record(step="triage_observations",
                                summary="no new observations",
                                count=0, status="noop")
        except Exception as e:
            print(f"[activity_log: {e}]")
        return

    print(f"[triage: {len(new_entries)} new observation(s) to process]")
    threads_written = []
    proposals_written = []
    total_cost = 0.0

    for obs in new_entries:
        thread_id = _new_thread_id(state)
        try:
            alice_response, llm_meta = _triage_one(obs, thread_id)
            total_cost += llm_meta["cost_usd"]
        except Exception as e:
            print(f"  ERROR on thread {thread_id}: {e}")
            continue
        path = _write_thread(obs, thread_id, alice_response, llm_meta)
        threads_written.append((thread_id, alice_response["classification"], path))
        prop_path = _maybe_propose(obs, thread_id, alice_response)
        if prop_path:
            proposals_written.append((thread_id, prop_path))
        print(f"  [{thread_id}] {alice_response['classification']} ({llm_meta['model']}, ${llm_meta['cost_usd']:.4f})")
        print(f"    summary: {alice_response['summary'][:80]}")

 # Update triage state
    if new_entries:
        state["last_processed_ts"] = max(e["ts_iso"] for e in new_entries if e["ts_iso"])
        _save_triage_state(state)

    print()
    print(f"summary: {len(threads_written)} threads opened, "
          f"{len(proposals_written)} proposals queued, "
          f"${total_cost:.4f} spent")
    try:
        from alice.persistence import activity_log
        n_threads = len(threads_written)
        n_props = len(proposals_written)
        summary = f"{n_threads} observation{'' if n_threads == 1 else 's'} triaged"
        if n_props:
            summary += f", {n_props} proposal{'' if n_props == 1 else 's'} queued for review"
        activity_log.record(
            step="triage_observations",
            summary=summary, count=n_threads, cost=total_cost,
            details={"threads": [t[0] for t in threads_written],
                     "proposals": [p[0] for p in proposals_written]},
        )
    except Exception as e:
        print(f"[activity_log: {e}]")


if __name__ == "__main__":
    main()
